### ISSUE TITLE
Required files not included or dependencies not listed

### ISSUE THREAD

**Issue by AFlowOfCode** [Seldaek/php-console#49]
I cloned the repository and php-console immediately failed at runtime due to this statement on line 47 of index.php: 

require 'vendor/autoload.php';

This file is not included, nor is it immediately obvious where to acquire it. I commented out the line, which allowed php-console to actually load the console. I then attempted to test a simple code, but in the right column received error:

Fatal error: Class 'SensioLabs\Melody\Resource\ResourceParser' not found in MelodyPlugin.php on line 17

Are these prerequisite dependencies? README mentions nothing of this, so either the issue is that they are missing and should be bundled, or that the instructions omit the fact that they must be installed separately as dependencies.

**Comment by staabm** [comment]
Install the dependencies after git clone with composer install
