### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by ribafs** [Seldaek/php-console#51]
I try to install only making download/clone e uncompress but not have vendor.
I try to install with composer:
composer create-project --stability=dev --keep-vcs seld/php-console
Error:
[InvalidArgumentException]                                  
  Could not find package seld/phpconsole with stability dev. 

Then I down package zip, uncompress and 
cd /var/www/html/php-console
composer update
And works.

Thank you for your work.

**Comment by Seldaek** [comment]
The error message lists the package name as seld/phpconsole and not seld/php-console so it looks to me like you had a typo or something?

**Comment by ribafs** [comment]
Em 01/10/2016 09:05, Jordi Boggiano escreveu: 

> The error message lists the package name as seld/phpconsole and not seld/php-console so it looks to me like you had a typo or something? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

I change project name to phpconsole and not php-console. 

This make diference? 

-- 
Colaborar é ser Humano!
 

Links:
------
[1]
https://github.com/Seldaek/php-console/issues/51#issuecomment-250908945
[2]

**Comment by Seldaek** [comment]
Well that's the package name so yes it matters, if you change the name 
it won't find it.

**Comment by ribafs** [comment]
Em 01/10/2016 11:00, Jordi Boggiano escreveu: 

> Well that's the package name so yes it matters, if you change the name 
> it won't find it. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

Ok. I undestund. Thank you. 

-- 
Colaborar é ser Humano!
 

Links:
------
[1]
https://github.com/Seldaek/php-console/issues/51#issuecomment-250913946
[2]
