### ISSUE TITLE
Script ended unexpectedly.

### ISSUE THREAD

**Issue by DavBE** [Seldaek/php-console#52]
Hi!

I get a "Script ended unexpectedly" error when running the following code : 

```
$d = new DateTime();
$i = new DateInterval('P2W');
$p = new DatePeriod($d, $i, 5);

< $p;
```

php-console is running in the php 7 built-in web server (PHP 7.0.8-0ubuntu0.16.04.3).

Am I doing something wrong ?

**Comment by Seldaek** [comment]
Can you try running that code in a simple php file with `php -r test.php` on the command line? Just to see if you get more details..

**Comment by DavBE** [comment]
Hi,

Thanks for your reply.

` php -r '$d = new DateTime();$i = new DateInterval("P2W");$p = new DatePeriod($d, $i, 5);'`

--> no output

**Comment by Seldaek** [comment]
Ah I see, I get `Fatal error: Uncaught Error: Writing to DatePeriod properties is unsupported in console\krumo\class.krumo.php on line 921`.. it seems krumo does some hackery that breaks with DatePeriod objects.. So just use `var_dump($p);` instead for this one. Sorry about that.

**Comment by DavBE** [comment]
Ok no problem. Thank you.
